[package]
name = "recorder"
version = "0.1.0"
authors = ["keringar <git@keringar.xyz>"]

[target.'cfg(windows)'.dependencies]
winapi = {version = "0.3.5", features = ["winuser", "psapi"]}

[dependencies]
image = "0.19.0"
failure = "0.1.2"
imageproc = "0.15.0"
